storage:
  base_path: ./data
  db_name: "deepbio_index"
  raw_data_dir: "raw"

data:
  obis_s3_url: "s3://obis-open-data/occurrence/*.parquet"
  min_depth: 200

model:
  # Using Nucleotide Transformer v2 (50M) - Stable on Windows CPU
  name: "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species"
  quantized: true

classification:
  k_neighbors_voting: 10
